### ISSUE TITLE
TODOs, Ideas and Feature Requests ✨

### ISSUE THREAD

**Issue by thatfiredev** [rosariopfernandes/bluetoothingspeaker#2]
I'm listing here all my ideas to this project. I'd create a different issue for each one of them, but since it's a long list, I'd rather list them all on a single issue and use this same one as a space where everyone can add their ideas or feature requests (FR). If an idea/FR needs further discussion, it shall go into a new issue.

## ✨ Almighty List:
- [x] Improve the UI (Done in #3);
- [ ] Connect to the Firebase Realtime Database to remote control the device. Remote controlled actions (may) include:
    - [x] Change device name (Done in #4);
    - [x] Pair and disconnect devices (Done in #4);
    - [ ] Manage list of devices and display current connected device;
    - [ ] Adjust ~volume~ (Done in #4) and brightness;
    - [ ] Change UI colors.
- [ ] Allow Selecting Wi-fi networks? (I have to check if their APIs allow this; but I believe they do);
- [x] Create a complimentary ~PWA~ app that connects to Firebase for remote control; [**update:** app is currently in a private repo. Decided to use a Flutter app instead of PWA]
- [ ] Create a dialogflow app that connects to Firebase for remote control with voice commands;
- [ ] Make the screen optional (this means finding other ways of input and output, such as the two points above);
- [ ] Create a Screensaver (can be a slide of all pictures stored in Cloud Firestore, or a screen displaying the current time and weather);
- [ ] Integrate the app with a streaming service to be able to play songs straight from the internet.
- [ ] Develop a website describing the project (will probably write a blog post as well)

Feel free to comment your idea or feature request below. 🙂

**Comment by thatfiredev** [comment]
In order to allow having a Screensaver and a streaming service (since these 2 will require new activities), I'm considering using a Service to listen to events at all times.
